export { default as Activity} from "./Activity"
export { default as Cancer} from "./Cancer"
export { default as LongWaits} from "./LongWaits"
export { default as OutPatients} from "./OutPatients"
export { default as Diagnostics} from "./Diagnostics"